root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go", "yaml", "yml", "toml"]
  exclude_dir = ["tmp", "vendor", "node_modules", "migrations", "docs", "bin"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
