// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, detail, ip_address)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, action, detail, ip_address, created_at
`

type CreateAuditLogParams struct {
	UserID    pgtype.UUID   `json:"user_id"`
	Action    string        `json:"action"`
	Detail    []byte        `json:"detail"`
	IPAddress *netip.Prefix `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog, arg.UserID, arg.Action, arg.Detail, arg.IPAddress)
	var i AuditLog
	err := row.Scan(&i.ID, &i.UserID, &i.Action, &i.Detail, &i.IPAddress, &i.CreatedAt)
	return i, err
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, action, detail, ip_address, created_at
FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(&i.ID, &i.UserID, &i.Action, &i.Detail, &i.IPAddress, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countAuditLogsByUser = `-- name: CountAuditLogsByUser :one
SELECT COUNT(*) FROM audit_logs WHERE user_id = $1
`

func (q *Queries) CountAuditLogsByUser(ctx context.Context, userID interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
