// Code generated by sqlc. DO NOT EDIT.

package sqlc

import "context"

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	CountAuditLogsByUser(ctx context.Context, userID interface{}) (int64, error)
}

var _ Querier = (*Queries)(nil)
